global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'oai-gnb'
    static_configs:
      - targets: ['192.168.50.10:9090']
  
  - job_name: 'oai-ue'
    static_configs:
      - targets: ['192.168.50.20:9090']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.50.60:8080']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
